// import "../../global-style.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body style={{backgroundColor: "#0f1115"}} className="bg-background">
        {children}
      </body>
    </html>
  );
}
